[package]
name = "shell"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"
test = false
bench = false

[[bin]]
name = "shell"
path = "main.rs"
test = false
bench = false

[dependencies]
utils = { path = "../utils" }

[profile.dev]
opt-level = 3
