[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kernel"
path = "main.rs"
test = false
bench = false

[dependencies]
spin = { workspace = true }
utils = { path = "../utils" }
owo-colors = { features = ["alloc"], version = "4.2.3" }

[profile.dev]
opt-level = 3
